version: "3.8"
services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 20717:20717
    networks:
      - mydockernet
    volumes:
      - app_mongo:/data/db
networks:
  mydockernet:
    driver: bridge
volumes:
  app_mongo:
